### Obtener listado de pedidos 
GET http://localhost:8080/sales-order

### Obtener un pedido a traves de un id
GET http://localhost:8080/sales-order/2

### Obtener líneas de un pedido
GET http://localhost:8080/sales-order/2/to_item

### Obtener detalles de una línea de un pedido
GET http://localhost:8080/sales-order/2/to_item/20


### Crear un pedido con sus líneas
POST http://localhost:8080/sales-order/salesOrder
Content-Type: application/json;IEEE754Compatible=true

{
"salesOrderType": "OR",
"salesOrganization": "4810",
"distributionChannel": "10",
"organizationDivision": "00",
"salesGroup": "",
"salesOffice": "",
"salesDistrict": "CO0001",
"soldToParty": "48100001",
"createdByUser": "CC0000000003",
"purchaseOrderByCustomer":"PEDIDO desde cliente externo api",
"to_Item": {
    "results": [
    {
    "material": "TG11",
    "requestedQuantity": "12",
    "salesOrderItem": "1",
    "requestedQuantityUnit": "PC",
    "itemGrossWeight": "6.00",
    "netAmount": "89"
    },
     {
    "material": "TG14",
    "requestedQuantity": "10",
    "salesOrderItem": "2",
    "requestedQuantityUnit": "PC",
    "itemGrossWeight": "6.00",
    "netAmount": "89"
    },
      {
    "material": "TG14",
    "requestedQuantity": "10",
    "salesOrderItem": "10",
    "requestedQuantityUnit": "PC",
    "itemGrossWeight": "6.00",
    "netAmount": "89"
      }

    ]
}
}

### Crear una línea a un pedido 
POST http://localhost:8080/sales-order/8/to_Item
Content-Type: application/json;IEEE754Compatible=true

{
    "material": "TG11",
    "requestedQuantity": "12",
    //"salesOrderItem": "1",
    "requestedQuantityUnit": "PC",
    "itemGrossWeight": "6.00",
    "netAmount": "89"
}

### Editar un pedido
PUT http://localhost:8080/sales-order/9
Content-Type: application/json;IEEE754Compatible=true

{
"purchaseOrderByCustomer":"PEDIDO editado desde cliente api"
}

### Eliminar un pedido
DELETE http://localhost:8080/sales-order/9

DELETE http://localhost:8080/sales-order/219

