POST https://port8080-workspaces-ws-r8zz5.us10.applicationstudio.cloud.sap/
Content-Type: application/json;IEEE754Compatible=true

{
    "cityName": "Manizales",
    "houseNumber": "",
    "postalCode": "69190",
    "streetName": "Calle 62 22 58"
}



